# Generated by Django 5.1.2 on 2024-10-20 09:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_id',
            field=models.CharField(default=uuid.UUID('fc6a5916-7d5b-4689-9b15-235d9f807078'), primary_key=True, serialize=False),
        ),
    ]
