# Generated by Django 5.1.2 on 2024-10-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_reviews_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_id',
            field=models.CharField(default='3af8d664-af39-4e14-b0b4-201b93542ef1', primary_key=True, serialize=False),
        ),
    ]
