# Generated by Django 5.1.2 on 2024-10-20 04:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(default=uuid.UUID('0c3bf706-8401-4b54-b30e-dcd7c41fd2ad'), primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=1000)),
            ],
        ),
    ]
