# Generated by Django 5.1.2 on 2024-10-20 09:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(default=uuid.UUID('c8a2ed23-a971-421f-a0f4-1c488a60a9cf'), primary_key=True, serialize=False),
        ),
    ]
