# Generated by Django 5.1.2 on 2024-10-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(default='6b7e772a-0475-4251-8f66-44cf98acfa3c', primary_key=True, serialize=False),
        ),
    ]
