# Generated by Django 5.1.2 on 2024-10-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(default='a0c522cd-260e-45bb-89fd-d4e8b6c53ed7', primary_key=True, serialize=False),
        ),
    ]
