# Generated by Django 5.1.2 on 2024-10-20 09:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.UUID('a0d8bdb1-d5d8-4fd9-a68a-6c90c51e7812'), primary_key=True, serialize=False),
        ),
    ]
