# Generated by Django 5.1.2 on 2024-10-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='95e5de5c-5848-4a08-9420-6ab78c1a2793', primary_key=True, serialize=False),
        ),
    ]
