# Generated by Django 5.1.2 on 2024-10-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='543cbf77-4050-4cb2-a9c2-2d8f98224604', primary_key=True, serialize=False),
        ),
    ]
